::@echo off
:: > Setup required Environment
:: -------------------------------------
set RAYLIB_DIR=C:\raylib
set PATH=%PATH%;%RAYLIB_DIR%\mingw\bin
cd %~dp0
:: .
:: > Compile all raylib web examples 
:: -------------------------------------
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_basic_window
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_keys
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_mouse
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_mouse_wheel
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_gamepad
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_multitouch
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_input_gestures
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_2d_camera
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_3d_camera_mode
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_3d_camera_free
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_3d_camera_first_person
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_3d_picking
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_world_screen
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_custom_logging
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_window_letterbox
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_drop_files
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_random_values
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_storage_values
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_vr_simulator
cmd /c mingw32-make PLATFORM=PLATFORM_WEB core/core_loading_thread
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_basic_shapes
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_bouncing_ball
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_colors_palette
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_logo_raylib
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_logo_raylib_anim
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_rectangle_scaling
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_lines_bezier
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_collision_area
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_following_eyes
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_easings_ball_anim
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_easings_box_anim
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_easings_rectangle_array
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_draw_ring
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_draw_circle_sector
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shapes/shapes_draw_rectangle_rounded
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_raylib_fonts
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_sprite_fonts
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_ttf_loading
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_bmfont_ttf
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_font_sdf
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_format_text
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_input_box
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_writing_anim
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_rectangle_bounds
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB text/text_unicode
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_logo_raylib
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_rectangle
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_srcrec_dstrec
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_image_drawing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_image_generation
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_image_loading
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_image_processing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_image_text
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_to_image
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_raw_data
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_particles_blending
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_npatch_drawing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_background_scrolling
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_sprite_button
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_sprite_explosion
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB textures/textures_bunnymark
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_animation
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_billboard
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_box_collisions
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_cubicmap
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_first_person_maze
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_geometric_shapes
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_material_pbr
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_mesh_generation
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_mesh_picking
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_obj_loading
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_obj_viewer
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_orthographic_projection
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_rlgl_solar_system
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_skybox
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_yaw_pitch_roll
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB models/models_heightmap
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_model_shader
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_shapes_textures
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_custom_uniform
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_postprocessing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_palette_switch
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_raymarching
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_texture_drawing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_texture_waves
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_julia_set
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB shaders/shaders_erastosthenes
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB audio/audio_module_playing
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB audio/audio_music_stream
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB audio/audio_raw_stream
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB audio/audio_sound_loading
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB physac/physics_demo
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB physac/physics_friction
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB physac/physics_movement
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB physac/physics_restitution
:: cmd /c mingw32-make PLATFORM=PLATFORM_WEB physac/physics_shatter
